from __future__ import annotations

MAX_ACTIVE_PERSONAL_GOALS = 10
MAX_ACTIVE_FAMILY_GOALS_PER_GROUP = 5
MAX_GOAL_TITLE_LENGTH = 80
MAX_GOAL_TAG_LENGTH = 32
MIN_GOAL_PRIORITY = 1
MAX_GOAL_PRIORITY = 5
DEFAULT_EXPECTED_RETURN_PCT = 12.0
MAX_TARGET_AMOUNT_INR = 100_000_000
MAX_DURATION_MONTHS = 600
FAMILY_GOAL_METADATA_KEY = "family_goal_id"
