/**
 * User-facing labels aligned with Web investor app (`Web/src/shared/config/copy.ts`).
 * Zynd Mitra console shows the same concepts with read-only / masked context.
 */

import { ZYND_MITRA_COPY } from "@/lib/zynd-mitra-copy";

export const DISTRIBUTOR_KYC_STEPS: Array<{ id: string; label: string }> = [
  { id: "pan", label: "PAN Card" },
  { id: "digilocker", label: "DigiLocker" },
  { id: "address", label: "Address" },
  { id: "personal", label: "Personal Info" },
  { id: "nominee", label: "Nominee" },
  { id: "bank", label: "Bank" },
  { id: "signature", label: "Signature" },
  { id: "esign", label: "eSign" },
  { id: "review", label: "Review" },
];

export const DISTRIBUTOR_CLIENT_COPY = {
  loadingProfile: "Loading client profile…",
  clientNotFound: "Client not found.",

  overview: {
    zyndClientCode: "Zynd client code",
    riskProfile: "Risk profile",
    mfa: "Two-Factor Authentication",
    mfaEnabled: "Enabled",
    mfaDisabled: "Not enabled",
    mfaBadgeOn: "2FA enabled",
    mfaBadgeOff: "2FA disabled",
    memberSince: "Member since",
  },

  kyc: {
    title: "KYC verification",
    description:
      "Same journey investors complete on Zynd — PAN, address, bank, and review steps.",
    overallLabel: "Overall status",
    stepCompleted: "Completed",
    stepPending: "Pending",
    stepNeedsAttention: "Needs attention",
    stepNotRequired: "Not required",
    badgeKraCompliant: "KRA compliant",
    badgeNewToKyc: "New to KYC",
    pathSignatureRequired: "Required",
    pathEsignRequired: "Required",
    identityNote: ZYND_MITRA_COPY.identityNoteMitraView,
    journeyLastStepLabel: "Last step",
    journeyInitiatedLabel: "KYC initiated",
    journeyKraComplianceLabel: "KRA compliance",
    journeyKraCompliant: "Compliant",
    journeyKraNonCompliant: "Non-compliant",
    journeyLastStepUnknown: "Not started",
    auditLogTitle: "KYC audit log",
    auditLogSearchPlaceholder: "Search audit log…",
    auditLogActionFilterLabel: "Action",
    auditLogEmpty: "No KYC activity recorded yet.",
    auditLogEmptyFiltered: "No audit entries match your search.",
    auditLogColumnWhen: "Date & time",
    auditLogColumnAction: "Action",
    auditLogColumnStep: "Step",
    auditLogColumnDetail: "Details",
    auditLogColumnActor: "Actor",
    auditLogColumnSource: "Source",
    auditLogActorInvestor: "Investor",
    auditLogActorSystem: "System",
    auditLogStepNone: "—",
  },

  portfolio: {
    title: "MF Portfolio",
    description: "Mutual fund holdings and snapshot values for this investor.",
    currentValue: "Current value",
    invested: "Invested",
    totalReturns: "Total returns",
    redeemableValue: "Redeemable value",
    chartTitle: "Portfolio trend",
    chartEmpty: "Invest or import holdings to plot portfolio growth.",
    holdingsTitle: "Mutual fund holdings",
    holdingsDescription: "Schemes held by this investor",
    holdingsEmpty:
      "No holdings yet. Invest or import CAS to see a portfolio here.",
    holdingsEmptyFiltered: "No holdings match your filters.",
    holdingsSearchPlaceholder: "Search holdings…",
    holdingsAmcFilterLabel: "AMC",
    holdingsColumnScheme: "Scheme",
    holdingsColumnUnits: "Units",
    holdingsColumnNav: "NAV",
    holdingsColumnInvested: "Invested",
    holdingsColumnCurrent: "Current value",
    holdingsColumnRedeemable: "Redeemable",
    holdingsColumnReturns: "Returns",
    holdingsUnknownAmc: "AMC not listed",
    holdingsFolio: (folio: string) => `Folio ${folio}`,
    holdingsAsOf: (date: string) => `As of ${date}`,
    units: (units: number) => `${units.toFixed(3)} units`,
  },

  activity: {
    totalSipsLabel: "Total SIPs",
    totalSipsHint: "Monthly and weekly SIPs",
    activeSipsLabel: "Active SIPs",
    activeSipsHint: "Currently running",
    cancelledSipsLabel: "Cancelled SIPs",
    cancelledSipsHint: "Closed plans",
    totalTransactionsLabel: "Total transactions",
    totalTransactionsHint: "Mutual fund orders",
    sipsSectionTitle: "SIPs",
    transactionsSectionTitle: "Transactions",
    subTabsAriaLabel: "SIPs and transactions views",
    subTabs: {
      sips: "SIPs",
      transactions: "Transactions",
    },
    searchSipsPlaceholder: "Search SIPs…",
    searchOrdersPlaceholder: "Search orders…",
    statusFilterLabel: "Status",
    orderTypeFilterLabel: "Order type",
    filtersEmptyDescription: "Adjust filters, search, or clear all to reset.",
    sipsEmpty: "No SIPs yet. Start one from mutual funds.",
    sipsEmptyFiltered: "No SIPs match your filters",
    transactionsEmpty: "No orders yet.",
    transactionsEmptyFiltered: "No orders match your filters",
    sipColumnPlan: "Plan",
    sipColumnScheme: "Scheme",
    sipColumnFrequency: "Frequency",
    sipColumnAmount: "Amount",
    sipColumnStatus: "Status",
    sipColumnNextDue: "Next due",
    orderColumnOrder: "Order",
    orderColumnScheme: "Scheme",
    orderColumnType: "Type",
    orderColumnAmount: "Amount",
    orderColumnStatus: "Status",
    orderColumnCreated: "Created",
    orderColumnDetails: "Details",
    orderViewDetails: "View",
    orderDetailTitle: "Transaction details",
    orderDetailAmount: "Amount",
    orderDetailChannel: "Channel",
    orderDetailCreated: "Placed on",
    orderDetailSettled: "Settlement date",
  },

  goals: {
    title: "Goals",
    description: "Progress toward personal and family targets",
    empty: "No goals yet. Set a target to start.",
    totalGoalsLabel: "Total goals",
    activeGoalsLabel: "Active goals",
    investedLabel: "Invested toward goals",
    totalGoalAmountLabel: "Total goal amount",
    amountInvestedLabel: "Amount invested",
    overallProgressLabel: "Overall progress",
    allGoalsTitle: "All goals",
    createAction: "Create goal",
    createDisabledHint:
      ZYND_MITRA_COPY.goalsNotAvailable,
    personal: "Personal",
    family: "Family",
    progress: "Goal progress",
    savedSoFar: "Saved so far",
    target: "Target",
    scopeLabel: "Scope",
    detailDescription: "Goal progress, target, and savings snapshot for this client.",
    investedBadge: "Invested",
    notInvestedBadge: "Not invested",
    status: {
      active: "Active",
      draft: "Draft",
      achieved: "Achieved",
      paused: "Paused",
    },
  },

  family: {
    empty: "No family groups yet.",
    allFamilyGroupsTitle: "All family groups",
    createFamilyGroupAction: "Create family group",
    createFamilyGroupDialogTitle: "Create family group",
    createFamilyGroupDialogDescription:
      "Name the group and add a short note for members. You can invite investors after it is created.",
    createFamilyGroupNameLabel: "Group name",
    createFamilyGroupNamePlaceholder: "e.g. Sharma family",
    createFamilyGroupDescriptionLabel: "Description",
    createFamilyGroupDescriptionPlaceholder: "What this group is for…",
    createFamilyGroupSubmit: "Create group",
    createFamilyGroupCancel: "Cancel",
    createFamilyGroupDisabledHint:
      ZYND_MITRA_COPY.familyGroupsNotAvailable,
    members: (count: number) => `${count} members`,
    activeGoals: (count: number) => `${count} active goals`,
    membersTileLabel: "Members",
    membersTileHint: "In this group",
    goalsTileLabel: "Active goals",
    goalsTileHint: "Shared family goals",
    roleTileLabel: "Your role",
    roleTileHintOwner: "Group head / owner",
    roleTileHintMember: "Member access",
    portfolioWidgetTitle: "Family portfolio",
    portfolioWidgetHint: "Combined AUM",
    groupHeadLabel: "Group head",
    viewGroupAction: "View group",
    summaryTotalValueLabel: "Total value",
    summaryTotalValueHint: "Combined family AUM",
    portfolioSectionTitle: "Family portfolio",
    portfolioSectionDescription: "Combined AUM and growth across all linked members.",
    contributionsTitle: "Member contributions",
    contributionsDescription: "Share of total family portfolio value.",
    contributionsMemberBadgesLabel: "Family members · select to highlight chart",
    contributionsRingTotalLabel: "Total",
    contributionsRingAriaLabel: (memberCount: number, totalFormatted: string) =>
      `Portfolio share by ${memberCount} members, combined ${totalFormatted}`,
    goalsSectionTitle: "Family goals",
    familyGoalCreatedBy: "Created by",
    familyGoalCreatedByOwner: "Group owner",
    familyGoalTypeLabel: "Goal type",
    familyGoalPriorityLabel: "Priority",
    familyGoalMembersInvested: "Family members invested",
    familyGoalAmountInvested: "Amount invested",
    familyGoalDetailsAction: "Details",
    familyGoalPriorityHigh: "High priority",
    familyGoalPriorityMedium: "Medium priority",
    familyGoalPriorityLow: "Low priority",
    familyGoalTypes: {
      home: "Home",
      education: "Education",
      car: "Car",
      wedding: "Wedding",
      retirement: "Retirement",
      custom: "Custom",
    } as const,
    familyGroupIdentityDescription:
      "Shared investments, goals, and portfolio visibility for everyone in this group.",
    goalsOwnerOnly: "Family goals are visible when you are the group owner.",
    membersTableTitle: "All members",
    membersSectionTitle: "Family members",
    membersSectionDescription: "Members in this group · contact shown for clients in your book.",
    membersSearchPlaceholder: "Search members…",
    membersRoleFilterLabel: "Role",
    membersBookFilterLabel: "In your book",
    membersBookFilterYourClient: "Your client",
    membersColumnMember: "Member",
    membersColumnRole: "Role",
    membersColumnEmail: "Email",
    membersColumnPhone: "Phone",
    membersColumnPortfolioShare: "Portfolio share",
    membersColumnSharePercent: "Share %",
    membersColumnActions: "Actions",
    membersViewClient: "View client",
    membersEmptyFiltered: "No members match your filters.",
    yourClientBadge: "Your client",
    contributionLabel: "Portfolio share",
  },

  referrals: {
    title: "Referrals",
    description: "Invite → Invest → Qualify — same program investors see on Zynd.",
    referralCode: "Referral code",
    totalReferrals: "Total referrals",
    kycVerified: "KYC verified",
    firstInvestment: "First investment",
    qualified: "Qualified",
  },

  devices: {
    title: "Your Devices",
    description: "Active sessions on this account (read-only).",
    lastActive: (date: string) => `Last active ${date}`,
    thisDevice: "This Device",
    otherDevice: "Other device",
    empty: "No active sessions found.",
  },

  identity: {
    title: "Profile",
    description: "Account and identity details (masked).",
    account: "Account",
    accountCardDescription: "Login and client identifiers.",
    identityDetails: "Identity Details",
    pan: "PAN",
    mobile: "Phone",
    email: "Email",
    copyContact: (label: string) => `Copy ${label}`,
    contactCopied: (label: string) => `${label} copied`,
    ifsc: "IFSC",
    copyIfsc: "Copy IFSC code",
    ifscCopied: "IFSC copied",
    valueNotAvailable: "Not on file",
    bankAccountsTitle: "Bank accounts",
    bankAccountsDescription: "Verified accounts linked for investments and payouts.",
    bankAccountsEmpty: "No bank accounts on file.",
    bankPrimary: "Primary",
    addressTitle: "Address",
    addressDescription: "KYC address on record (city and region only).",
    addressEmpty: "No address on file.",
    connectedAccountsTitle: "Connected sign-in",
    connectedAccountsDescription: "Google and Apple linked to this Zynd account.",
    google: "Google",
    apple: "Apple",
    connected: "Connected",
    notConnected: "Not connected",
  },

  tabs: {
    portfolio: "Portfolio",
    kyc: "KYC",
    documents: "Documents",
    risk: "Risk profile",
    goals: "Goals",
    family: "Family",
    transactions: "SIPs & Transactions",
    ariaLabel: "Client profile sections",
  },

  documents: {
    empty: "No KYC documents on file for this client.",
    emptyFiltered: "No documents match your filters.",
    tableTitle: "Client documents",
    searchPlaceholder: "Search documents…",
    statusFilterLabel: "Status",
    statusUploaded: "Uploaded",
    statusMissing: "Missing",
    statusNotRequired: "Not required",
    columnDocument: "Document",
    columnIdentifier: "ID / reference",
    columnFile: "File",
    columnUploaded: "Uploaded",
    columnStatus: "Status",
    columnSource: "Source",
    identifierNone: "—",
    fileNone: "—",
    dateNone: "—",
    viewDescription: "Preview and metadata for this document.",
    viewPreviewLabel: "Document preview",
    viewMissingBody: "This document has not been uploaded yet.",
    viewNotRequiredBody: "Not required for this client's KYC path.",
    download: "Download",
    downloading: "Downloading…",
  },

  riskProfile: {
    tabDescription: "Completed assessments and investor risk tolerance (read-only).",
    profileCreatedBadge: "Risk profile created",
    notCreatedBadge: "Not assessed",
    createAction: "Create risk profile",
    createDisabledHint:
      ZYND_MITRA_COPY.riskNotAvailable,
    assessmentsTitle: "All assessments",
    pastAssessmentsTitle: "Past assessments",
    pastAssessmentsEmpty: "No prior assessments on record.",
    latestHeroEyebrow: "Latest risk profile",
    pastAssessmentTrendsTitle: "Past assessment trends",
    assessmentsEmpty: "No risk assessments on record for this client.",
    currentAssessment: "Current",
    listAriaLabel: "Risk profile assessments",
    detailTitle: "Risk profile detail",
    detailDescription: "Score, tier, and guidance from this assessment.",
    scoreLabel: "Risk score",
    downloadPdf: "Download PDF",
    downloadingPdf: "Downloading…",
    viewAction: "View report",
    viewAnswers: "View answers",
    viewAnswersTitle: "Assessment answers",
    viewAnswersDescription: "Questions and responses from this completed assessment.",
    viewAnswersLoading: "Loading answers…",
    viewAnswersEmpty: "No answers found for this assessment.",
    viewAnswersLoadFailed: "Could not load answers.",
  },
} as const;

export function kycStepLabelForId(stepId: string): string {
  return DISTRIBUTOR_KYC_STEPS.find((step) => step.id === stepId)?.label ?? stepId;
}

export function formatKycOverallStatus(status: string): string {
  const normalized = status.toLowerCase();
  if (normalized === "completed" || normalized === "verified") return "KYC verified";
  if (normalized === "submitted" || normalized === "under_review") return "Under review";
  if (normalized === "none" || !status) return "Not started";
  return status.replace(/_/g, " ");
}

export function kycProgressPct(completedCount: number, total: number): number {
  if (total <= 0) return 0;
  return Math.min(100, Math.round((completedCount / total) * 100));
}
