/** User-facing product term — use instead of "distributor" in UI copy. */
export const ZYND_MITRA_COPY = {
  singular: "Zynd Mitra",
  plural: "Zynd Mitras",
  add: "Add Zynd Mitra",
  addJourney: "Add Zynd Mitra journey",
  assign: "Assign Zynd Mitra",
  branchMitra: "Branch Zynd Mitra",
  onboarding: "Zynd Mitra onboarding",
  legalName: "Zynd Mitra name",
  submit: "Submit Zynd Mitra",
  notFound: "Zynd Mitra not found in this branch.",
  searchPlaceholder: "Search Zynd Mitras…",
  searchAria: "Search Zynd Mitras",
  searchIncentiveAria: "Search incentive by Zynd Mitra",
  branchListAria: "Branch Zynd Mitras",
  emptyFiltered: "No Zynd Mitras match your filters",
  loading: "Loading Zynd Mitras",
  loadingTable: "Loading Zynd Mitras table",
  byMitra: "By Zynd Mitra",
  incentiveByMitra: "Incentive by Zynd Mitra",
  netSalesByMitra: "MTD net sales by Zynd Mitra",
  netSalesAria: "Net sales by Zynd Mitra",
  sipLumpsumAria: "SIP versus lumpsum by Zynd Mitra",
  schemeIncentiveAria: "Incentive by scheme category and Zynd Mitra",
  workEmailDesc: "Enter the Zynd Mitra work email. We will send a one-time code to their inbox.",
  inboxOtpDesc: "Check the Zynd Mitra inbox for the 6-digit code.",
  mobileDesc: "Enter the Indian mobile number linked to this Zynd Mitra account.",
  panDesc: "Enter the Zynd Mitra's Permanent Account Number for AMFI and compliance checks.",
  mappedToBranch: "Zynd Mitras mapped to your branch",
  appName: "Zynd Mitra",
  consoleName: "Zynd Mitra Console",
  consoleHome: "Zynd Mitra Console home",
  loadingConsole: "Loading Zynd Mitra console",
  consoleSessions: "Sessions where you are signed in to the Zynd Mitra console.",
  console2faSoon:
    "Two-factor is not set up on this account yet. Enrollment from the Zynd Mitra console will be available soon.",
  passwordNotWired: "Password change is not wired for the Zynd Mitra console yet.",
  needsMitraAction: "Needs Zynd Mitra action",
  mitraArn: "Zynd Mitra ARN",
  proposedMitra: "Proposed Zynd Mitra",
  mitraLinked: "Zynd Mitra linked",
  linkingMitra: "Linking Zynd Mitra…",
  assignDialogDesc:
    "Send the investor a confirmation email. The Zynd Mitra is linked only after they approve via the magic link.",
  assignDialogBody:
    "We email the investor a secure link. Their Zynd Mitra is linked only after they confirm.",
  assignNotePlaceholder: "Optional note for the Zynd Mitra",
  noCommissionData: "No commission data for this Zynd Mitra.",
  kycClearForMitra: "KYC and compliance exceptions are clear for this Zynd Mitra.",
  adjustPeriodMitra: "Adjust period, Zynd Mitra, or search to reset.",
  adjustEntryMitra: "Adjust entry type, Zynd Mitra, or search to reset.",
  adjustStageMitra: "Adjust Zynd Mitra, stage, or search to reset.",
  yourBookArn: "Only clients linked to your Zynd Mitra ARN (demo).",
  txnAwaitingMitra: "Single-fund recommendations you sent from quick transaction.",
  fullBookDesc:
    "Full investor book for this Zynd Mitra — onboarding, compliance, and investment status at a glance.",
  targetsPerMitra: "Targets vs actuals for each Zynd Mitra.",
  complianceQueueDesc: "KYC queue and clients needing Zynd Mitra action",
  adminContact: "To update Zynd Mitra details or replace documents, contact your Zynd administrator.",
  onboardNew: "Onboard a new Zynd Mitra to",
  viewBranchMitras: "View branch Zynd Mitras",
  mitraAccount: "Zynd Mitra account",
  mitraCode: "Zynd Mitra code",
  mitraVerification: "Aadhaar and PAN submitted for Zynd Mitra verification",
  onboardingIncomplete: "Zynd Mitra onboarding incomplete — EUIN validation",
  mitraDetails: "Zynd Mitra details",
  leaveApplicationDesc: "Approve or decline a Zynd Mitra leave application",
  welcomeConsole: "Welcome to Zynd Mitra Console",
  identityNoteMitraView: "Verified from PAN and KYC records (masked for Zynd Mitra view).",
  goalsNotAvailable: "Investors create and manage goals in the Zynd app. Zynd Mitra-initiated goals are not available yet.",
  familyGroupsNotAvailable: "Creating family groups from the Zynd Mitra console is not available yet. Investors set up and manage groups in the Zynd app.",
  riskNotAvailable: "Investors complete the risk questionnaire in the Zynd app. Zynd Mitra-initiated assessments are not available yet.",
  searchTitle: "Zynd Mitra search",
  signInSubtitle: "Sign in with your Zynd Mitra console account.",
  demoAccountError: "Invalid email or password. Use a demo Zynd Mitra account.",
  noConsoleAccess: "This account does not have Zynd Mitra console access.",
  defaultRoleLabel: "Zynd Mitra",
  mitraCodeCopied: "Zynd Mitra code copied",
  copyMitraCode: (code: string) => `Copy Zynd Mitra code ${code}`,
  bookTransactionsAria: "Zynd Mitra book transactions",
  mitraClientsAria: "Zynd Mitra clients",
  mitraSipsAria: "Zynd Mitra SIPs",
  profileSectionsAria: "Zynd Mitra profile sections",
  statusSummaryAria: "Zynd Mitra status summary",
  statusSummaryCounts: (active: number, former: number, paused: number, total: number) =>
    `${active} active, ${former} former, ${paused} paused of ${total} Zynd Mitras`,
  tableColumnMitra: "Zynd Mitra",
  yourBook: "Your Zynd Mitra book",
  bookSchemeMixInfo:
    "Scheme mix across your Zynd Mitra book as of Jul 2026. Segments show AUM share by asset class.",
  bookSipMandatesInfo: "Number of live SIP mandates in your Zynd Mitra book each month.",
  verifyEmailOtpDesc: "Enter the Zynd Mitra work email and confirm with the inbox OTP.",
  verifyMobileOtpDesc: "Indian mobile number and SMS OTP for login and txn alerts.",
  holdingsAcrossBook: "Scheme-wise holdings, units, and market value across the Zynd Mitra book.",
  onboardingsInBook: "New onboardings, activations, and churn in this Zynd Mitra's book.",
  onboardingsYourBook: "New onboardings, activations, and churn in your Zynd Mitra book.",
  reportClosingAumDesc: "Closing AUM by Zynd Mitra and product category for HO finance.",
  reportNetSalesDesc: "Gross inflow, redemptions, and net sales by Zynd Mitra.",
  kycFollowUpDesc: "Open KYC cases and exceptions requiring Zynd Mitra follow-up.",
  branchAssignmentRequiredTitle: "Branch assignment required",
  branchAssignmentRequiredDesc:
    "Your State Head must assign you to a branch before you can onboard Zynd Mitras or add clients.",
} as const;
