from __future__ import annotations

RISK_PROFILE_DEFAULT_ATTEMPTS = 6
RISK_PROFILE_UNLOCK_BONUS_ATTEMPTS = 3
RISK_PROFILE_UNLOCK_OTP_PURPOSE = "risk_profile_unlock"
RISK_PROFILE_TRENDS_MIN_PROFILES = 3
