import { appConfig } from "@/shared/config/app-config";
import { APP_NAME, APP_TAGLINE } from "@/shared/config/brand";

const otpDigits = appConfig.otpLength;

export const copy = {
  meta: {
    siteDescription:
      "Manage, grow, and understand your financial life through a secure, intelligent platform.",
  },
  auth: {
    welcomeTitle: `Welcome to ${APP_NAME}`,
    welcomeDescription: "Sign in or create an account to continue.",
    loginTitle: "Welcome back",
    loginDescription: `Enter your password to sign in to ${APP_NAME}.`,
    joinTitle: `Join ${APP_NAME}`,
    joinEmailOtpMessage: (email: string) =>
      `A ${otpDigits}-digit code was sent to ${email}. Enter it below to join ${APP_NAME}.`,
    dialogSrTitle: `Login or Sign up to ${APP_NAME}`,
    joinButton: `Join ${APP_NAME}`,
    continueWithGoogle: "Continue with Google",
    continueWithApple: "Continue with Apple",
    googleNotConfigured: "Google Sign-In is not configured yet.",
    appleNotConfigured: "Apple Sign-In is not configured yet.",
    mfaAuthenticatorHint: `Open your authenticator app and enter the ${otpDigits}-digit code.`,
    mfaAuthenticatorForApp: `Open your authenticator app and enter the code shown for ${APP_NAME}.`,
    otpEmailError: `Enter the ${otpDigits}-digit code sent to your email.`,
    otpMobileError: `Enter the ${otpDigits}-digit code sent to your mobile.`,
    otpMobileBanner: `Enter the ${otpDigits}-digit OTP sent to your mobile number.`,
    otpAuthenticatorError: `Enter the ${otpDigits}-digit code from your authenticator app.`,
    otpEmailChange: `Enter the ${otpDigits}-digit code sent to`,
    referralCodeToggle: "Have a referral code?",
    referralCodeToggleHide: "Hide referral code",
    referralCodePlaceholder: "Referral Code",
    referralCodeHint: "Applied when you create a new account.",
    referralCodeInvalid: "Enter a valid referral code (6–16 letters or numbers).",
  },
  account: {
    profileOnApp: `Your profile information on ${APP_NAME}.`,
    reconnecting: `Reconnecting to ${APP_NAME}...`,
    resetPasswordIntro: `Choose a new password for your ${APP_NAME} account.`,
    deletionGracePeriod: (days = appConfig.deletionGracePeriodDays) =>
      `Your account enters a ${days}-day grace period before permanent deletion.`,
    deletionGracePeriodShort: (days = appConfig.deletionGracePeriodDays) =>
      `Your account enters a ${days}-day grace period. You can cancel before deletion runs.`,
    deletionPasswordPrompt: (days = appConfig.deletionGracePeriodDays) =>
      `Enter your current password to start the ${days}-day deletion grace period.`,
    deletionCancelDuringGrace: "You can cancel the request anytime during the grace period.",
    deletionPermanentAfterDays: (days = appConfig.deletionGracePeriodDays) =>
      `After ${days} days, your data and access will be permanently removed.`,
    deletionScheduledSuccess: (when: string) =>
      `Account deletion scheduled for ${when}. You can cancel before then.`,
    deletionScheduledSuccessGeneric: "Account deletion scheduled. You can cancel before it runs.",
    deletionCancelled: "Account deletion cancelled.",
    deletionCouldNotRequest: "Could not request account deletion.",
    deletionCouldNotCancel: "Could not cancel deletion.",
    maxActiveDevices: (max = appConfig.maxActiveDevices) =>
      `Active sessions signed into your account. Up to ${max} devices at once.`,
  },
  resetPassword: {
    invalidLinkTitle: "Invalid reset link",
    invalidLinkDescription: "Request a new password reset from the sign-in screen.",
    successTitle: "Password updated",
    successDescription: "You can now sign in with your new password.",
    title: "Reset your password",
    invalidLinkError: "Invalid reset link.",
    weakPasswordError: "Choose a stronger password.",
    mfaRequiredError: "Enter your authenticator code or a backup code to continue.",
    couldNotReset: "Could not reset password.",
    backToHome: "Back to home",
    backToSignIn: "Back to sign in",
    newPasswordPlaceholder: "New password",
    authenticatorPlaceholder: "Authenticator code",
    backupCodePlaceholder: "Or backup code",
    updating: "Updating...",
    updatePassword: "Update password",
  },
  settings: {
    profileTitle: "Profile",
    bankAccountTitle: "Bank Account",
    bankAccountDescription: "Your verified bank account used for investments and payouts.",
    bankAccountSectionTitle: "Linked Bank Account",
    bankAccountEmptyTitle: "No Bank Account on File",
    bankAccountEmptyDescription: "Complete KYC and verify your bank account to see it here.",
    profileLoading: "Loading your KYC profile…",
    identitySectionTitle: "Identity Details",
    identitySectionDescription: "Verified from your PAN and KYC records.",
    addressSectionTitle: "Address",
    personalDetailsTitle: "Personal Details",
    accountSectionTitle: "Account",
    fullNameLabel: "Full Name",
    emailLabel: "Email",
    phoneLabel: "Phone",
    countryLabel: "Country",
    googleLabel: "Google",
    appleLabel: "Apple",
    notSet: "Not set",
    notConnected: "Not connected",
    connected: "Connected",
    connectGoogle: "Connect Google",
    disconnectGoogle: "Disconnect Google",
    connectApple: "Connect Apple",
    disconnectApple: "Disconnect Apple",
    working: "Working...",
    googleNotConfigured: "Google Sign-In is not configured yet.",
    appleNotConfigured: "Apple Sign-In is not configured yet.",
    googleConnectedSuccess: "Google account connected.",
    appleConnectedSuccess: "Apple account connected.",
    couldNotLoadConnections: "Could not load connected accounts.",
    couldNotConnectGoogle: "Could not connect Google.",
    couldNotConnectApple: "Could not connect Apple.",
    couldNotDisconnectAccount: "Could not disconnect account.",
    disconnectOAuthTitle: (provider: "Google" | "Apple") => `Disconnect ${provider}`,
    disconnectPasswordDescription: "Enter your current password to disconnect this sign-in method.",
    disconnectMfaDescription: "Enter your authenticator code to disconnect this sign-in method.",
    disconnectSubmit: "Disconnect",
    mfaTitle: "Two-Factor Authentication",
    mfaDescription: "Manage MFA and backup codes for your account.",
    mfaActiveTitle: "MFA Is Active",
    mfaInactiveTitle: "MFA Is Not Enabled",
    mfaEnabledBadge: "Enabled",
    mfaNotSetUpBadge: "Not Set Up",
    mfaEnrolledOn: (when: string) => `Enrolled on ${when}.`,
    mfaEnableHint: "Enable MFA before you transfer or invest funds.",
    changeAuthenticator: "Change Authenticator",
    disableMfa: "Disable MFA",
    backupCodesTitle: "Backup Codes",
    backupCodesRemaining: (remaining: number, total: number) => `${remaining} of ${total} remaining`,
    backupCodesDescription: "One-time codes for account recovery if you lose your authenticator.",
    copyCodes: "Copy Codes",
    regenerateCodes: "Regenerate Codes",
    backupCodesMissingHint:
      "Backup codes are only shown once after setup. Regenerate new codes if you did not save them.",
    zyndPinTitle: "Zynd PIN",
    zyndPinDescription: "Quick 4-digit unlock for your account on web and mobile.",
    zyndPinEnrolledHint:
      "Unlock your account quickly after idle time or when returning to this browser.",
    changePasswordTitle: "Change Password",
    changePasswordDescription: "Re-authentication required. Other sessions will be signed out.",
    changePasswordSecurityTitle: "Before You Continue",
    changePasswordSecurityHint:
      "You'll confirm your identity with your current password. If MFA is enabled, your authenticator code is required too.",
    changePasswordStaySignedIn: "You'll stay signed in on this device.",
    changePasswordCurrentLabel: "Current Password",
    changePasswordCurrentPlaceholder: "Enter current password",
    changePasswordNewLabel: "New Password",
    changePasswordNewPlaceholder: "Create a new password",
    changePasswordSubmit: "Update Password",
    changePasswordSubmitting: "Updating...",
    changePasswordSuccess: "Password updated. Other sessions were signed out.",
    changePasswordWeakError: "New password does not meet all requirements.",
    changePasswordFailed: "Could not change password.",
    changePasswordMfaTitle: "Confirm Password Change",
    changePasswordMfaDescription: "Enter your authenticator code to update your password.",
    changeEmailTitle: "Change Email",
    changeEmailDescription: "Update the email address linked to your Zynd account.",
    changeEmailCurrentLabel: "Current Email",
    changeEmailNewLabel: "New Email Address",
    changeEmailNewPlaceholder: "name@example.com",
    changeEmailPasswordLabel: "Current Password",
    changeEmailPasswordPlaceholder: "Enter current password",
    changeEmailCodeInfo: "A verification code will be sent to your new email address, not your current one.",
    changeEmailSubmit: "Send Verification Code",
    changeEmailSubmitting: "Sending code...",
    changeEmailVerifyTitle: "Verify Your New Email",
    changeEmailConfirmSubmit: "Confirm New Email",
    changeEmailConfirmSubmitting: "Confirming...",
    changeEmailBack: "Back",
    changeEmailResend: "Resend Code",
    changeEmailResendIn: (seconds: number) => `Resend in ${seconds}s`,
    changeEmailCodeSent: "Verification code sent to your new email address.",
    changeEmailResendSuccess: "A new verification code was sent.",
    changeEmailSuccess: "Email updated successfully.",
    changeEmailInvalid: "Enter a valid email address.",
    changeEmailSameError: "New email must be different from your current email.",
    changeEmailStartFailed: "Could not start email change.",
    changeEmailResendFailed: "Could not resend code.",
    changeEmailConfirmFailed: "Could not confirm email change.",
    changeEmailMfaTitle: "Confirm Email Change",
    changeEmailMfaDescription: "Enter your authenticator code to start the email update.",
    devicesTitle: "Your Devices",
    devicesThisDevice: "This Device",
    devicesUnknown: "Unknown Device",
    devicesLastActive: (when: string) => `Last active ${when}`,
    devicesSignOut: "Sign Out",
    devicesSigningOut: "Signing Out...",
    devicesSignOutAllOthers: "Sign Out All Other Devices",
    devicesEmpty: "No active sessions found.",
    devicesLoadFailed: "Could not load sessions.",
    devicesRevokeFailed: "Could not revoke session.",
    devicesRevokeAllFailed: "Could not revoke sessions.",
    notificationsTitle: "Notifications",
    notificationsPreferencesTitle: "Notification Preferences",
    notificationsPreferencesDescription: "Choose how you receive email and in-app updates.",
    notificationsTableCategory: "Category",
    notificationsTableEmail: "Email",
    notificationsTableInApp: "In-App",
    notificationsEmailRequired: "Required",
    notificationsLoadFailed: "Could not load notification preferences.",
    notificationsSaveFailed: "Could not save notification preference.",
    notificationsRetry: "Retry",
    notificationsCategorySecurityTitle: "Security Alerts",
    notificationsCategorySecurityDescription: "Sign-ins, password changes, MFA, and device activity.",
    notificationsCategoryKycTitle: "KYC Updates",
    notificationsCategoryKycDescription: "Verification started, under review, completed, or rejected.",
    notificationsCategoryReferralTitle: "Referral Activity",
    notificationsCategoryReferralDescription:
      "Signups, KYC verified, first investment, qualified, and engaged milestones.",
    notificationsCategoryAccountTitle: "Account Updates",
    notificationsCategoryAccountDescription: "Profile and settings changes on your account.",
    deleteAccountTitle: "Delete Account",
    deleteAccountDescription: "Permanently remove your account after a grace period.",
    deletionHowItWorksTitle: "How It Works",
    deletionStepGraceTitle: (days = appConfig.deletionGracePeriodDays) => `${days}-Day Grace Period`,
    deletionStepGraceDescription: "Your account is paused and scheduled for removal.",
    deletionStepCancelTitle: "Cancel Anytime",
    deletionStepCancelDescription: "Sign in before the deadline to stop deletion and keep your account.",
    deletionStepFinalTitle: "Permanent Removal",
    deletionStepFinalDescription: (days = appConfig.deletionGracePeriodDays) =>
      `After ${days} days, your profile, KYC data, and activity are deleted.`,
    deletionActionTitle: "Ready to Delete Your Account?",
    deletionActionDescription: "You'll confirm your password before the request is submitted.",
    deletionScheduledTitle: "Deletion Scheduled",
    deletionScheduledDateLabel: "Scheduled For",
    deletionScheduledBodyHint: "Sign in anytime before this date to cancel and restore your account.",
    deletionKeepAccountHint: "Want to keep your account? Cancel the request below.",
    deletionPendingBadge: "Pending",
    deletionScheduledDescription: (when: string) =>
      `Your account is scheduled for permanent deletion on ${when}. Sign in anytime before then to cancel.`,
    deletionBeforeYouContinueTitle: "Before You Continue",
    cancelDeletionRequest: "Cancel Deletion Request",
    cancellingDeletion: "Cancelling...",
    requestAccountDeletion: "Request Account Deletion",
    confirmAccountDeletionTitle: "Confirm Account Deletion",
    confirmAccountDeletionMfaDescription: "Enter your authenticator code to schedule account deletion.",
    requestDeletion: "Request Deletion",
    profilePhotoAlt: "Profile Photo",
    accountFallbackName: "Account",
  },
  uploadDialog: {
    chooseFile: "Choose a File",
    dropHint: "Click or drag and drop your file here",
    browse: "Browse Files",
    change: "Choose a Different File",
    save: "Upload",
    cancel: "Cancel",
    uploading: "Uploading...",
    uploadFailed: "Could not upload file.",
    applyCrop: "Apply Crop",
    cropping: "Applying...",
  },
  profilePhoto: {
    title: "Update Profile Photo",
    description: "Upload a clear photo of yourself. It is stored securely and scanned before use.",
    choosePhoto: "Choose a Photo",
    dropHint: "Click or drag and drop your photo here",
    browse: "Browse Files",
    changePhoto: "Choose a Different Photo",
    save: "Save Photo",
    cancel: "Cancel",
    uploading: "Uploading...",
    uploadFailed: "Could not upload profile photo.",
    editAriaLabel: "Edit Profile Photo",
    previewAlt: "Profile Photo Preview",
    formats: (maxMb: number, minDim: number, maxDim: number) =>
      `JPG, PNG, WEBP, or HEIC · ${minDim}px min · up to ${maxDim}px · ${maxMb} MB max`,
  },
  kyc: {
    menuLabel: "KYC verification",
    pageTitle: "Identity verification",
    pageDescription: "Complete KYC to unlock investments and transfers on Zynd.",
    completeTitle: "KYC verified",
    completeDescription: "Your identity has been verified. You can now invest and transfer funds.",
    pendingTitle: "Under review",
    pendingDescription:
      "We're reviewing your KYC submission. This usually takes a short while — we'll update your status once it's complete.",
    verifiedPanLabel: "Verified PAN",
    submittedPanLabel: "Submitted PAN",
    backToDashboard: "Back to dashboard",
    done: "Done",
    verifiedPan: (pan: string) => `Verified PAN: ${pan}`,
    submittedPan: (pan: string) => `Submitted PAN: ${pan}`,
    exitConfirm: {
      title: "Exit KYC verification?",
      description:
        "Your progress will be saved, but you need to finish verification before investing or transferring funds.",
      confirm: "Exit verification",
      cancel: "Continue KYC",
    },
    mfaGate: {
      title: "Set up MFA first",
      description:
        "Two-factor authentication is required before you can start KYC verification.",
      setupButton: "Set up MFA",
      menuDisabledHint: "Complete account verification before starting KYC",
    },
    entryGate: {
      title: "Complete account setup",
      description: "Verify your contact details and secure your account before starting KYC.",
      email: "Verify your email address.",
      phone: "Verify your mobile number.",
      mfa: "Enable two-factor authentication (MFA).",
      pin: "Set up your Zynd PIN.",
      accountInactive: "Your account is not active.",
      setupMfa: "Set up MFA",
      setupPin: "Set up Zynd PIN",
      openSettings: "Open settings",
    },
    loading: "Loading your KYC progress…",
    bootstrapLoadingTitle: "Loading KYC",
    bootstrapErrorTitle: "Couldn't load KYC",
    bootstrapErrorDescription:
      "We couldn't load your verification progress. Check your connection and try again.",
    bootstrapErrorServer:
      "We couldn't reach the server to load your KYC progress. Please try again in a moment.",
    bootstrapErrorAuth: "Your session may have expired. Sign in again, then reopen KYC verification.",
    bootstrapRetry: "Try again",
    bootstrapRetrying: "Retrying…",
    saving: "Saving…",
    phase1CompleteTitle: "Section saved",
    phase1CompleteDescription:
      "Your PAN, address, and personal details are saved. You can continue with bank and nominee details later.",
    phase1CompleteCta: "Save and continue later",
    phase2CompleteTitle: "Details saved",
    phase2CompleteDescription:
      "Your nominee and bank details are saved. Continue with signature and review to submit KYC.",
    submittedTitle: "KYC submitted",
    submittedDescription:
      "Your KYC application has been submitted to the KRA. Check status below once processing completes.",
    checkStatusAction: "Check KYC status",
    checkStatusChecking: "Checking KRA status…",
    checkStatusPendingTitle: "Still under review",
    checkStatusPendingDescription:
      "Your KYC is still pending at the KRA. Please check again after some time.",
    checkStatusDone: "Close",
    submitFailedTitle: "Submission failed",
    journeySaveFailed: "Could not save your progress. Check your connection and try again.",
    continue: "Continue",
    back: "Back",
    stepOf: (step: number, total: number) => `Step ${step} of ${total}`,
    steps: {
      panCard: "PAN Card",
      address: "Address",
      personalInfo: "Personal Info",
      nominee: "Nominee",
      bank: "Bank",
      signature: "Signature",
      review: "Review",
    },
    placeholders: {
      address: "Residential address details will be collected in this step.",
      personalInfo: "Personal information will be collected in this step.",
      nominee: "Nominee details will be collected in this step.",
      bank: "Bank account details will be collected in this step.",
      review: "Review all entered details before final submission.",
      submit: "Submit your KYC application for verification.",
    },
    pan: {
      newToKycBadge: "New to KYC",
      kraRegisteredBadge: "KRA registered",
      kycUpdateRequiredBadge: "KYC update required",
      kycOnHoldBadge: "KYC on hold",
      kycStatusUnclearBadge: "KYC status unclear",
      kycCheckPendingBadge: "KRA check pending",
      stepDescription: [
        "Enter your Permanent Account Number",
        "exactly as it appears on your PAN card.",
      ] as const,
      numberLabel: "PAN number",
      numberPlaceholder: "ABCDE1234F",
      firstNameLabel: "First name",
      middleNameLabel: "Middle name",
      lastNameLabel: "Last name",
      namePendingTitle: "Name as per PAN card",
      namePendingDescription: "Will be fetched when you continue.",
      nameFetchingTitle: "Fetching name from PAN",
      nameFetchingDescription: "This usually takes a few seconds.",
      nameFetchedTitle: "Name as per PAN card",
      nameFetchedDescription: "Add your middle name if it appears on your PAN.",
      middleNameInputPlaceholder: "Enter middle name",
      fetching: "Fetching PAN details...",
      fetchFailed: "Could not fetch name for this PAN. Try again.",
      invalidPan: "Enter a valid 10-character PAN number.",
      verifyPan: "Verify PAN",
      dateOfBirthLabel: "Date of birth",
      panCategoryLabel: "PAN type",
      panCategoryIndividual: "Individual",
      panCategoryCorporate: "Corporate",
      corporatePanTitle: "Corporate PAN not supported",
      corporatePanDescription:
        "Individual KYC cannot be completed with a corporate PAN card. Use an individual PAN to continue.",
      verificationFailedTitle: "PAN verification failed",
      verificationFailedDescription: "We could not verify your PAN details. Review the information and try again.",
      readinessBlockedTitle: "KYC not available",
      readinessBlockedDescription: "Your KRA readiness status prevents starting KYC right now.",
      blockDialogClose: "Understood",
      continue: "Continue",
    },
    address: {
      digilockerPrefillHint: "Address prefilled from DigiLocker. Please review and edit if needed.",
      permanentTab: "Permanent address",
      correspondenceTab: "Correspondence address",
      sameAsPermanent: "Correspondence address is same as permanent address",
      requiredField: "This field is required.",
      invalidPincode: "Enter a valid 6-digit pincode.",
      invalidLine1: "Address line 1 must be 3-120 characters.",
      invalidLine2: "Address line 2 must be 120 characters or fewer.",
      invalidCity: "City must be 2-60 characters.",
      fields: {
        line1: "Address line 1",
        line2: "Address line 2",
        city: "City",
        state: "State",
        statePlaceholder: "Select state",
        pincode: "Pincode",
        country: "Country",
      },
      placeholders: {
        line1: "House no., building, street",
        line2: "Area, landmark (optional)",
        city: "City",
        state: "State",
        pincode: "110001",
        country: "India",
      },
    },
    personalInfo: {
      requiredField: "This field is required.",
      invalidFathersName: "Enter a valid name using letters only (2-80 characters).",
      invalidPlaceOfBirth: "Enter a valid place of birth (2-80 characters, letters only).",
      fields: {
        fathersName: "Father's name",
        gender: "Gender",
        incomeSlab: "Income slab",
        occupation: "Occupation",
        maritalStatus: "Marital status",
        pepExposed: "Politically exposed person (PEP)",
        placeOfBirth: "Place of birth",
        nationality: "Nationality",
      },
      placeholders: {
        fathersName: "As per official records",
        select: "Select",
        placeOfBirth: "City, state / country",
      },
    },
    nominee: {
      addNominee: "Add nominee",
      addNomineeTitle: "Add nominee",
      editNominee: "Edit nominee",
      saveNominee: "Save nominee",
      cancel: "Cancel",
      next: "Next",
      back: "Back",
      continue: "Continue",
      remove: "Remove",
      maxNominees: "You can add up to 3 nominees.",
      unsavedBanner:
        "You have unsaved nominee details. Finish adding your nominee or use Continue below.",
      requiredField: "This field is required.",
      invalidDob: "Select a valid date of birth.",
      invalidShare: "Enter a share between 1 and 100.",
      shareExceedsTotal: "Total nominee share cannot exceed 100%.",
      invalidFullName: "Enter a valid name using letters only (2-80 characters).",
      invalidEmail: "Enter a valid email address.",
      invalidMobile: "Enter a valid 10-digit Indian mobile number.",
      invalidDocumentNumber: "Enter a valid number for the selected document type.",
      invalidPan: "Enter a valid 10-character PAN number.",
      invalidAadhaar: "Enter a valid 12-digit Aadhaar number.",
      invalidPassport: "Enter a valid passport number (e.g. A1234567).",
      invalidDrivingLicence: "Enter a valid driving licence number (6-20 characters).",
      invalidVoterId: "Enter a valid Voter ID (e.g. ABC1234567).",
      invalidAddressLine1: "Address line 1 must be 3-120 characters.",
      invalidAddressLine2: "Address line 2 must be 120 characters or fewer.",
      invalidCity: "City must be 2-60 characters.",
      selectDocumentTypeFirst: "Select document type first",
      types: {
        minor: "Minor",
        individual: "Individual",
      },
      wizardSteps: {
        basic: "Basic",
        contact: "Contact",
        address: "Address",
      },
      fields: {
        fullName: "Nominee full name",
        relationship: "Relationship",
        sourceOfWealth: "Source of wealth",
        dateOfBirth: "Date of birth",
        sharePercent: "Nominee share (%)",
        documentType: "Document type",
        documentNumber: "Document number",
        email: "Email",
        mobile: "Mobile",
        addressLine1: "Address line 1",
        addressLine2: "Address line 2 (optional)",
        city: "City",
        pincode: "PIN code",
        country: "Country",
        guardianName: "Guardian name",
        guardianSourceOfWealth: "Guardian source of wealth",
        guardianEmail: "Guardian email",
        guardianMobile: "Guardian mobile",
        nomineeAddress: "Nominee address",
      },
      placeholders: {
        fullName: "Enter full name",
        dateOfBirth: "dd/mm/yyyy",
        sharePercent: "e.g. 50",
        documentNumber: "Enter document number",
        documentPan: "ABCDE1234F",
        documentAadhaar: "123456789012",
        documentPassport: "A1234567",
        documentDrivingLicence: "DL1420110012345",
        documentVoterId: "ABC1234567",
        email: "name@example.com",
        mobile: "Mobile number",
        addressLine1: "House no., building, street",
        addressLine2: "Area, landmark",
        city: "City",
        pincode: "110001",
        guardianName: "Enter guardian name",
        select: "Select",
      },
      hints: {
        guardianIdentity: "Provide one identity document for Guardian (choose any one).",
        nomineeIdentity: "Provide one identity document for Nominee (choose any one).",
      },
      list: {
        introTitle: "Who should receive your holdings?",
        introDescription:
          "Add up to 3 nominees with share allocation. This step is optional — you can continue without adding one.",
        emptyTitle: "No nominees added yet",
        emptyDescription: "Tap below to add your first nominee and assign their share percentage.",
        slotsLabel: (count: number, max: number) => `${count} of ${max} nominees`,
        totalShare: (share: number) => `${share}% allocated`,
        shareLabel: (share: string) => `${share}% share`,
        resumeAdd: "Continue adding",
      },
      unsavedBannerTitle: "Unsaved nominee details",
    },
    bank: {
      requiredField: "This field is required.",
      invalidAccountNumber: "Account number must be 9-18 digits.",
      invalidIfsc: "Enter a valid 11-character IFSC code.",
      fetchFailed: "Could not fetch bank account details. Try again.",
      verifyFailed: "Bank verification failed. Try again.",
      fetching: "Fetching account details...",
      verifying: "Verifying bank account...",
      verify: "Verify",
      namePendingTitle: "Name as per bank account",
      namePendingDescription: "Will be fetched when you continue.",
      manualPendingTitle: "Bank verification needs your help",
      manualPendingDescription:
        "Upload a bank statement below. After verification, you will continue through signature and eSign.",
      nameFetchingTitle: "Fetching account details",
      nameFetchingDescription: "This usually takes a few seconds.",
      nameFetchedTitle: "Name as per bank account",
      nameFetchedDescription: "Confirm your bank details before verifying.",
      verifyingTitle: "Verifying bank account",
      verifyingDescription: "Matching your account with bank records.",
      verifiedTitle: "Bank account verified",
      verifiedDescription: "Your account is ready for investments and transfers.",
      fields: {
        accountNumber: "Account Number",
        accountType: "Account Type",
        ifscCode: "IFSC Code",
        accountHolderName: "Account Holder Name",
        bankName: "Bank Name",
        branch: "Branch",
      },
      placeholders: {
        accountNumber: "Enter account number",
        ifscCode: "HDFC0001234",
        select: "Select",
      },
      badges: {
        panVerified: "PAN verified",
        bankVerified: "Bank verified",
        readinessVerified: "Readiness verified",
        readinessPending: "Readiness pending",
      },
      manualVerifyTitle: "Manual verification required",
      manualVerifyDescription:
        "Cybrilla could not verify your bank account automatically. Upload a recent bank statement or cancelled cheque (PDF, JPEG, or PNG).",
      manualVerifyEsignNote:
        "After your proof is accepted, continue KYC. You will complete signature and Aadhaar eSign before submission.",
      uploadProof: "Upload bank statement",
      proofUploading: "Uploading proof…",
      proofUploaded: "Proof uploaded",
      proofUploadFailed: "Could not upload bank proof. Try again.",
      proofRequired: "Upload bank proof before continuing.",
      verifyManual: "Verify with proof",
    },
    signature: {
      drawTab: "Draw sign",
      uploadTab: "Upload sign",
      drawHint: "Sign inside the box using your mouse or finger.",
      uploadHint: "Upload a clear image of your signature.",
      uploadTitle: "Upload signature image",
      uploadFormats: "PNG, JPG, or WEBP up to 4 MB",
      chooseImage: "Choose image",
      removeImage: "Remove",
      clearPad: "Clear",
      previewAlt: "Signature preview",
      drawRequired: "Draw your signature before continuing.",
      uploadRequired: "Upload a signature image before continuing.",
      invalidFileType: "Upload a PNG, JPG, or WEBP image.",
      fileTooLarge: "Image must be 4 MB or smaller.",
      saving: "Saving signature…",
      processing: "Verifying signature…",
      saveFailed: "Could not save your signature. Try again.",
    },
    digilocker: {
      title: "DigiLocker",
      description:
        "You will be redirected to DigiLocker to fetch your verified documents. Keep this window open until verification finishes.",
      redirecting: "Redirecting to DigiLocker",
      secondsRemaining: (seconds: number) => `${seconds}s`,
      failedTitle: "DigiLocker not completed",
      failedDescription:
        "Aadhaar was not fetched. In DigiLocker, select the Aadhaar checkbox and complete verification before returning.",
      retry: "Try DigiLocker again",
      cancel: "Close",
    },
    esign: {
      title: "Aadhaar eSign",
      description:
        "You will be redirected to complete Aadhaar-based eSign. Keep this window open until verification finishes.",
      redirecting: "Redirecting to eSign",
      secondsRemaining: (seconds: number) => `${seconds}s`,
    },
    location: {
      title: "Location required",
      description:
        "We need your current location to complete Aadhaar eSign. Disable VPN or mock location apps, then allow location access in your browser.",
      enable: "Enable location",
      requesting: "Getting location…",
      cancel: "Close",
      denied: "Location access is required for eSign. Allow location in your browser settings and try again.",
      unavailable: "Could not detect your location. Check device settings and try again.",
      timeout: "Location request timed out. Try again.",
      unsupported: "Your browser does not support location access. Use a supported browser to continue.",
      inaccurate: "Could not confirm your precise location. Move to an open area and try again.",
      spoofDetected: "Mock or spoofed location detected. Disable fake GPS apps and try again.",
      required: "Location access is required to complete KYC eSign.",
    },
    review: {
      descriptionLines: [
        "Review your details below.",
        "Submit when everything looks correct.",
      ] as const,
      submit: "Submit KYC",
      submitting: "Submitting your KYC application…",
      notProvided: "Not provided",
      fullName: "Full name",
      signatureMethod: "Signature method",
      nominee: {
        emptyTitle: "No nominee added yet",
        emptyDescription:
          "Nominees are optional, but adding one helps ensure your holdings go to the right person.",
        emptySummary: "Optional - tap to add a nominee",
        addNominee: "Add nominee",
      },
      kycVerifiedBadge: "✅ KYC verified",
      pan: {
        verifiedTitle: "PAN verified",
        verifiedDescription: "Details fetched from your PAN card and DigiLocker.",
        verifiedBadge: "✅ PAN verified",
      },
      bank: {
        verifiedTitle: "Bank account verified",
        verifiedDescription: "Your account is ready for investments and transfers.",
        verifiedBadge: "✅ Bank verified",
      },
      sections: {
        pan: "PAN details",
        address: "Address",
        personalInfo: "Personal information",
        nominee: "Nominees",
        bank: "Bank account",
        signature: "Signature",
      },
    },
  },
  confirmDialog: {
    confirm: "Confirm",
    cancel: "Cancel",
    done: "Done",
  },
  mfa: {
    fundEligibilityTitle: "Enable MFA to Move Funds",
    fundEligibilityDescription: "Two-factor authentication is required before transfers or investments.",
    setupButton: "Set Up MFA",
    backupCodesOfflineHint: "Keep these codes offline. You will not see them again.",
    backupAccess: {
      reveal: "Reveal Backup Codes",
      pinTitle: "Enter Zynd PIN",
      pinDescription: "Confirm your PIN to view your saved backup codes.",
      passwordTitle: "Confirm Your Password",
      passwordDescription: "Enter your account password to view your saved backup codes.",
      usePasswordInstead: "Use Account Password Instead",
      invalidPin: "Invalid Zynd PIN.",
      invalidPassword: "Invalid password.",
      hiddenHint: "Backup codes are hidden. Verify yourself to view, copy, or download them.",
    },
    orEnterManually: "Or Use Setup Key",
    verifying: "Verifying...",
    continue: "Continue",
    preparing: "Preparing...",
    enroll: {
      startTitle: "Enable two-factor authentication",
      startDescription: "Required before you can transfer or invest funds.",
      confirmTitle: "Scan your authenticator",
      confirmDescription: "Scan the QR code or copy the setup key.",
      backupTitle: "Save your backup codes",
      backupDescription: "Each code works once if you lose access to your authenticator.",
      benefits: [
        "Protects your account when moving money",
        "Works with any standard authenticator app",
        "Backup codes are shown once — store them safely",
      ] as const,
      verifyAndEnable: "Verify and enable MFA",
      successTitle: "MFA is enabled",
      successDescription: "Two-factor authentication is active on your account.",
      downloadBackupCodesJson: "Download JSON",
      couldNotStart: "Could not start MFA enrollment.",
      invalidCode: "Invalid authenticator code.",
    },
    reset: {
      verifyTitle: "Verify current authenticator",
      confirmTitle: "Set up new authenticator",
      confirmDescription: "Scan the new QR code and verify with a code from the new app entry.",
      backupTitle: "Save new backup codes",
      backupDescription: "Your old backup codes no longer work. Store these new codes safely.",
      confirmNewAuthenticator: "Confirm new authenticator",
      couldNotVerify: "Could not verify authenticator code.",
      invalidCode: "Invalid verification code.",
    },
    disable: {
      srTitle: "Disable authenticator",
      title: "Disable authenticator",
      description:
        "Confirm your identity to turn off multi-factor authentication. Other sessions will be signed out.",
      disabling: "Disabling...",
      submit: "Disable MFA",
      couldNotDisable: "Could not disable MFA.",
    },
    regenerate: {
      srTitle: "Regenerate backup codes",
      title: "Regenerate backup codes",
      description: "Confirm your identity to issue a new set of one-time backup codes.",
      regenerating: "Regenerating...",
      submit: "Generate new backup codes",
      couldNotRegenerate: "Could not regenerate backup codes.",
    },
  },
  pin: {
    lockTitle: "Enter your Zynd PIN",
    lockDescription: "Unlock your account to continue.",
    setupTitle: "Set up Zynd PIN",
    setupDescription: "Required before you can transfer or invest funds.",
    setupSteps: {
      verifyTitle: "Verify it's you",
      verifyDescription: "Confirm your password and authenticator code to continue.",
      pinTitle: "Create your PIN",
      pinDescription: "Choose a 4-digit PIN you'll use to unlock Zynd on this device.",
      successTitle: "Zynd PIN is ready",
      successDescription: "Use it to unlock after idle time or when you return to this browser.",
    },
    setupBenefits: [
      "Required before transfers and investments",
      "Unlocks your account after idle time",
      "Separate from your login password",
    ] as const,
    setupVerifyHint: "We verify your identity before letting you create a PIN.",
    setupStepPassword: "Confirm your password",
    setupStepMfa: "Enter authenticator code",
    setupStepCreate: "Create your 4-digit PIN",
    setupStepConfirm: "Confirm your PIN",
    setupSuccess: "Zynd PIN is ready. Use it to unlock your account on this device.",
    pinMismatch: "PIN entries do not match.",
    verifyButton: "Unlock",
    forgotLink: "Forgot PIN?",
    forgotTitle: "Reset Zynd PIN",
    forgotDescription: "We sent a verification code to your email.",
    sendResetCode: "Send reset code",
    resetButton: "Reset PIN",
    setUpButton: "Set Up Zynd PIN",
    enrolledLabel: "PIN Active",
    notEnrolledLabel: "Not Set Up",
    mfaRequiredHint: "Enable MFA before you can set up Zynd PIN.",
    fundEligibilityTitle: "Set Up Zynd PIN to Move Funds",
    fundEligibilityDescription:
      "After MFA is enabled, create your 4-digit Zynd PIN to unlock transfers and investments.",
    invalidPin: "Incorrect PIN. Try again.",
    pinLocked: "PIN is temporarily locked. Reset via email or try again later.",
    couldNotVerify: "Could not verify PIN.",
    couldNotSetup: "Could not set up Zynd PIN.",
    couldNotReset: "Could not reset PIN.",
    biometricTitle: "Unlock with biometrics",
    biometricDescription: "Use Touch ID, Windows Hello, or your device fingerprint.",
    biometricPrompt: "Waiting for biometric verification…",
    biometricUsePin: "Use PIN instead",
    biometricEnableTitle: "Fingerprint Unlock",
    biometricEnableDescription:
      "Use Touch ID or Windows Hello to unlock Zynd on this device. Your PIN remains the fallback.",
    biometricEnableButton: "Enable on this device",
    biometricEnabledLabel: "Enabled on this device",
    biometricNotAvailable: "Biometric unlock is not available in this browser.",
    biometricCouldNotEnable: "Could not enable biometric unlock.",
    biometricRemoveButton: "Remove from this device",
  },
  referral: {
    pageDescription: "Invite friends to Zynd and track link activity as the rewards program rolls out.",
    shareTitle: "Your Referral Link",
    shareHint: "Share your link or QR code. We'll count it the moment someone opens your invite.",
    shareMessage: "Join me on Zynd — open this invite link: {url}",
    shareNativeTitle: "Join Me on Zynd",
    shareEmailSubject: "You're Invited to Zynd",
    socialWhatsApp: "WhatsApp",
    socialX: "X",
    socialLinkedIn: "LinkedIn",
    socialEmail: "Email",
    socialMore: "More",
    copyLink: "Copy Link",
    copied: "Copied",
    qrButton: "QR Code",
    qrDialogTitle: "Referral QR Code",
    qrDialogDescription: "Scan or download this code to share your invite link.",
    downloadQr: "Download QR Code",
    downloadQrLoading: "Downloading...",
    qrAlt: "Referral QR Code",
    summaryTotalReferrals: "Total Referrals",
    summaryTotalEarnings: "Total Earnings",
    summarySuccessfulReferrals: "Successful Referrals",
    summaryReferralsThisMonth: "+{count} this month",
    summaryNoReferralsThisMonth: "No new referrals this month",
    summaryEarningsThisMonth: "+{amount} this month",
    summaryNoEarningsThisMonth: "Rewards launch soon",
    summaryConversionRate: "{rate} conversion rate",
    leaderboardTitle: "Referral Leaderboard",
    leaderboardMoreCount: "+5",
    leaderboardMoreHint: "Top Performers This Month",
    leaderboardViewAll: "View Full Leaderboard",
    leaderboardPageTitle: "Referral Leaderboard",
    leaderboardPageDescription: "See who is leading referrals this month and how much they have earned.",
    leaderboardPageSubtitle: "Top Referrers This Month",
    leaderboardLastUpdated: "Last updated: {datetime}",
    leaderboardTableRank: "Rank",
    leaderboardTableUser: "User",
    leaderboardTableReferrals: "Referrals",
    leaderboardTableEarnings: "Earnings",
    leaderboardReferralsCountShort: "{count} Referrals",
    leaderboardDoingGreatTitle: "You're Doing Great!",
    leaderboardDoingGreatTopPercent: "top {percent}%",
    leaderboardDoingGreatSubtitleLead: "You are in the",
    leaderboardDoingGreatSubtitleSuffix: "of all referrers",
    leaderboardYourRank: "Your Rank",
    leaderboardTotalReferralsLabel: "Total Referrals",
    leaderboardTotalEarningsLabel: "Total Earnings",
    leaderboardShareYourLink: "Share Your Link",
    leaderboardRecentReferrals: "Recent Referrals",
    leaderboardStatusCompleted: "Completed",
    leaderboardStatusPending: "Pending",
    leaderboardReferralsCount: "{count} Referrals",
    leaderboardEarningsLabel: "Earnings",
    leaderboardYouLabel: "You",
    leaderboardPeriodThisMonth: "This Month",
    leaderboardEmpty: "No leaderboard data yet. Share your link to get started.",
    leaderboardEmptyTitle: "Leaderboard Coming Soon",
    leaderboardEmptySubtitle: "You'll see top referrers here soon. Share your link to get the rankings started.",
    leaderboardPodiumLockedTitle: "Spot Locked",
    leaderboardPodiumLockedSubtitle: "More referrers needed to unlock this rank",
    leaderboardTableInsufficientTitle: "Not Enough Data Yet",
    leaderboardTableInsufficientSubtitle:
      "The full rankings table appears once more referrers join this month.",
    leaderboardNoRank: "—",
    earningsOverviewTitle: "Earnings Overview",
    earningsPeriodThisMonth: "This Month",
    earningsPeriodLast3Months: "Last 3 Months",
    earningsPeriodAllTime: "All Time",
    earningsGrowth: "+{amount} ({percent}%)",
    earningsNoGrowth: "+₹0 (0.0%)",
    earningsChartAriaLabel: "Referral earnings trend chart",
    earningsLockedTitle: "Refer & Earn",
    earningsLockedSubtitle: "Share your link to unlock your earnings insights",
    codeLabel: "Referral Code",
    copyCodeLabel: "Copy Referral Code",
    loading: "Loading your referral link...",
    loadFailed: "Could not load your referral link.",
    referralsTitle: "Your Referrals",
    referralsPageTitle: "Your Referrals",
    referralsPageDescription: "Track everyone who joined through your link and where they are in the journey.",
    referralsPageSubtitle: "Full List of People Referred by You",
    referralsFilterAll: "All Statuses",
    referralsFilterOnboarded: "Onboarded",
    referralsFilterKyc: "KYC Completed",
    referralsFilterInvested: "Capital Invested",
    referralsSearchPlaceholder: "Search Referrals",
    referralsEmpty: "No one has signed up with your link yet.",
    referralsEmptyTitle: "No Signups Yet",
    referralsFilterEmpty: "No referrals match your search or filters.",
    referralsJoinedToday: "Joined today",
    referralsJoinedYesterday: "Joined yesterday",
    referralsJoinedDaysAgo: "Joined {count} days ago",
    referralsJoinedWeekAgo: "Joined 1 week ago",
    referralsJoinedWeeksAgo: "Joined {count} weeks ago",
    referralsJoinedMonthAgo: "Joined over a month ago",
    referralsViewAll: "View All Referrals",
    referralsTotalCount: "{count} Total Referrals",
    referralProgressOnboarded: "Onboarded",
    referralProgressKyc: "KYC Completed",
    referralProgressInvested: "Capital Invested",
    referralStageSignedUp: "Signed Up",
    referralStageKycVerified: "KYC Verified",
    referralStageFirstInvestment: "First Investment",
    referralStageQualified: "Qualified",
    referralStageEngaged: "Engaged",
    referralProductMutualFund: "Mutual Fund",
    referralProductFixedDeposit: "Fixed Deposit",
    referralProductOther: "Investment",
    referralChannelEmail: "Email Signup",
    referralChannelGoogle: "Google Signup",
    referralChannelApple: "Apple Signup",
    stageTitle: "How Referrals Work",
    steps: [
      {
        label: "Invite",
        description:
          "Share your link or QR code. When someone opens it and signs up on Zynd, they are linked to you.",
      },
      {
        label: "Invest",
        description: "They complete KYC verification and make their first investment on Zynd.",
      },
      {
        label: "Qualify",
        description:
          "They hold that investment, stay active, and unlock referral rewards as they progress.",
      },
    ],
    landingLoading: "Opening your invite...",
    landingInvalid: "This referral link is not valid.",
  },
  dashboard: {
    sectionFallback: `Manage this section of your ${APP_NAME} dashboard.`,
    defaultDescription: `Your ${APP_NAME} wealth dashboard.`,
    error: {
      boundaryTitle: "Something went wrong",
      boundaryDescription:
        "Try again. If the problem continues, refresh the page or sign out and back in.",
      retry: "Try again",
    },
    security: {
      newDevice:
        "You signed in from a new device. We sent a security email to your registered address.",
      velocityFlagged:
        "We flagged unusual sign-in activity on your account. Review your active sessions if this wasn't you.",
      reviewDevices: "Review your devices",
    },
  },
  marketing: {
    heroTagline: APP_TAGLINE.toUpperCase(),
    heroHeadline: "Your financial life, unified and intelligent.",
    heroLead: (appName: string = APP_NAME) =>
      `${appName} helps individuals and families manage, grow, and understand their`,
    heroSublead:
      "wealth through a secure, premium experience built on trust, growth, and innovation.",
    featureCards: [
      { label: "Portfolio", value: "Track all assets in one place" },
      { label: "Goals", value: "Plan and monitor your future" },
      { label: "Insights", value: "AI-powered financial guidance" },
    ] as const,
  },
  mutualFunds: {
    tabBrowse: "Browse",
    tabOrders: "Orders",
    tabHoldings: "External holdings",
    catalogTitle: "Explore funds",
    catalogDescription: "{count} active funds available to invest",
    catalogEmpty: "No categories are visible yet. Catalog promotion runs after AMC empanelment and scheme sync.",
    catalogLoadError: "Unable to load mutual fund catalog.",
    loadingCatalog: "Loading catalog…",
    featuredTitle: "Featured funds",
    featuredDescription: "Curated picks from your investment categories",
    categoryFundCount: "{count} funds",
    categoryEmpty: "No funds are available in this category right now.",
    categoryLoadError: "Unable to load category funds.",
    loadingCategory: "Loading category…",
    loadingFunds: "Loading funds…",
    loadingMore: "Loading more…",
    loadMore: "Load more funds",
    backToBrowse: "Back to browse",
    fundUnavailable: "This fund is not available in the catalog.",
    loadingFund: "Loading fund details…",
    navChartTitle: "NAV trend",
    navChartDescription: "Trailing 1-year NAV history",
    returnsTitle: "Returns",
    disclaimerTitle: "Important information",
    distributorArn: "ARN",
    distributorEuin: "EUIN",
    investTitle: "Invest",
    investDescription: "Place a lumpsum order in this scheme",
    minLumpsum: "Min lumpsum",
    minSip: "Min SIP",
    amountLabel: "Investment amount (₹)",
    amountPlaceholder: "Enter amount",
    invalidAmount: "Enter a valid investment amount.",
    minLumpsumError: "Minimum lumpsum for this fund is {amount}.",
    placeOrder: "Place lumpsum order",
    placingOrder: "Placing order…",
    orderSuccess: "Order submitted — status: {status}.",
    orderFailed: "Unable to place order. Try again.",
    ordersDisabled: "Order placement is temporarily unavailable.",
    investGated: "Complete MFA and PIN setup to place mutual fund orders.",
    ordersTitle: "Your orders",
    ordersDescription: "Recent mutual fund purchase requests",
    ordersEmpty: "You have not placed any mutual fund orders yet.",
    ordersLoadError: "Unable to load orders.",
    loadingOrders: "Loading orders…",
    unknownFund: "Unknown fund",
    holdingsTitle: "External holdings",
    holdingsDescription: "Schemes imported from your consolidated account statement",
    holdingsEmpty: "No external holdings yet. Import your CAS to see holdings held outside Zynd.",
    holdingsLoadError: "Unable to load external holdings.",
    loadingHoldings: "Loading holdings…",
    unknownAmc: "Unknown AMC",
    casImportCta: "Import CAS",
    casImporting: "Requesting import…",
    casImportRequested: "CAS import requested — status: {status}.",
    casImportFailed: "Unable to request CAS import.",
    casDisabled: "External holdings import is not enabled yet.",
    fundFactsTitle: "Fund facts",
    benchmarkLabel: "Benchmark",
    fundManagerLabel: "Fund manager",
    amcDescriptionLabel: "About the AMC",
    amcWebsiteLabel: "Visit AMC website",
    searchPlaceholder: "Search by fund name, ISIN, or AMC…",
    searchHint: "Type at least 2 characters to search",
    searchEmpty: "No funds matched your search.",
    searchLoadError: "Unable to search funds.",
    searching: "Searching…",
    searchResultsCount: "{count} results for “{query}”",
    investmentDetailsTitle: "Investment details",
    investmentDetailsDescription: "Minimum amounts and supported transaction types from the fund platform",
    oneTimeInvestmentTitle: "One-time investment",
    additionalInvestmentTitle: "Additional investment",
    redemptionTitle: "Redemption",
    sipOptionsTitle: "SIP options",
    sipFrequency: "Frequency",
    sipMinInstallments: "Min installments",
    investmentMin: "Min",
    investmentMax: "Max",
    investmentMultiples: "Multiples",
    redemptionMinUnits: "Min units",
    redemptionUnitMultiples: "Unit multiples",
    transactionTypesTitle: "Supported transactions",
    transactionPurchase: "Purchase",
    transactionSip: "SIP",
    transactionRedemption: "Redemption",
    transactionSwitch: "Switch",
    transactionSwp: "SWP",
    transactionStp: "STP",
  },
  authSteps: {
    mfaChallenge: {
      title: "Two-factor authentication",
      description: "Enter the code from your authenticator app.",
    },
    oauthLink: {
      title: "Confirm account linking",
      description: "Verify your existing account before linking a sign-in provider.",
    },
    emailOtp: {
      title: `Join ${APP_NAME}`,
      description: "Verify your email with the one-time code we sent you.",
    },
    password: {
      title: "Create your password",
      description: "Choose a strong password to secure your account.",
    },
    mobile: {
      title: "Verify your mobile",
      description: "Enter your mobile number to receive an OTP.",
    },
    mobileOtp: {
      title: "Confirm mobile OTP",
      description: "Enter the code sent to your mobile number.",
    },
    profile: {
      title: "Complete your profile",
      description: "Tell us your name to finish setting up your account.",
    },
    forgotPassword: {
      title: "Reset your password",
      description: "We will send a reset link to your registered email.",
    },
  },
} as const;
